### ISSUE TITLE
README updates to account for Brew changes on Apple Silicone 

### ISSUE THREAD

**Issue by thekbb** [slushpupie/mildly-offend-me#5]
`$HOMEBREW_CELLAR`, the install location for homebrew was hard-coded in examples. Homebrew moved the default location on M1 and M2 macs see https://github.com/Homebrew/brew/issues/9177

The examples will not work on newer machines, which I'm sure @slushpupie has sprung for.

**Comment by slushpupie** [comment]
Acceptable request.
